Display stats for all parsed tweets
sachinkamath/fakemenot pull request #14
Opened 2017-10-07 17:46 UTC by ThrowsException

Hopefully this is what you were after for displaying all the tweets that were retrieved. I also updated the print statements so they should now work with both python 2/3

2017-10-07 19:06 UTC, pwnfoo requested changes

2017-10-07 19:06 UTC, sachinkamath commented on fakemenot/__init__.py
> +            elif removal_rate  < 50.0:
Hey, great idea. Lets skip <50 so that it doesn't spam the terminal a lot. Thanks for the PR :)

Just pass if rate is less than 50

2017-10-07 19:49 UTC, ThrowsException commented
Updated

2017-10-08 05:09 UTC, pwnfoo approved these changes

2017-10-08 05:16 UTC, merged

2017-10-08 05:16 UTC, sachinkamath commented
@ThrowsException Thanks! 💃